---
service: es-config-loader
provider:
  name: aws
  deploymentBucket:
    name: spp-results-${self:custom.environment}-serverless
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  memorySize: 1024
  timeout: 20
  tracing:
    lambda: true
  package:
    individually: true

custom:
  environment: ${env:ENVIRONMENT}

functions:
  deploy-config-loader:
    name: es-config-loader
    handler: config_loader.lambda_handler
    role: arn:aws:iam::#{AWS::AccountId}:role/lambda_invoke_lambda
    package:
      individually: true
      include:
        - config_loader.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      bucket_name: spp-results-${self:custom.environment}
      step_function_arn: arn:aws:states:eu-west-2:#{AWS::AccountId}:stateMachine
      file_path: configs/
      payload_reference_name: survey
      config_suffix: _config
      survey_arn_prefix: :ES-
      survey_arn_suffix: -Results

plugins:
  - serverless-latest-layer-version
  - serverless-pseudo-parameters
